version: '3.8'

services:
  # 知识表示环境 / Knowledge Representation Environment
  kr-eval:
    build:
      context: ../dockerfiles/knowledge-representation
      dockerfile: Dockerfile
    image: ghcr.io/kg/kr-eval:1.0.0
    container_name: kg-kr-eval
    volumes:
      - ../../../:/workspace
      - kr-cache:/workspace/.cache
    environment:
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

  # 图论环境 / Graph Theory Environment
  gt-eval:
    build:
      context: ../dockerfiles/graph-theory
      dockerfile: Dockerfile
    image: ghcr.io/kg/gt-eval:1.0.0
    container_name: kg-gt-eval
    volumes:
      - ../../../:/workspace
      - gt-cache:/workspace/.cache
    environment:
      - CUDA_VISIBLE_DEVICES=1
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

  # 语义分析环境 / Semantic Analysis Environment
  sa-eval:
    build:
      context: ../dockerfiles/semantic-analysis
      dockerfile: Dockerfile
    image: ghcr.io/kg/sa-eval:1.0.0
    container_name: kg-sa-eval
    volumes:
      - ../../../:/workspace
      - sa-cache:/workspace/.cache
    environment:
      - CUDA_VISIBLE_DEVICES=2
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

  # 本体工程环境 / Ontology Engineering Environment
  oe-eval:
    build:
      context: ../dockerfiles/ontology-engineering
      dockerfile: Dockerfile
    image: ghcr.io/kg/oe-eval:1.0.0
    container_name: kg-oe-eval
    volumes:
      - ../../../:/workspace
      - oe-cache:/workspace/.cache
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

  # 知识抽取环境 / Knowledge Extraction Environment
  ke-eval:
    build:
      context: ../dockerfiles/knowledge-extraction
      dockerfile: Dockerfile
    image: ghcr.io/kg/ke-eval:1.0.0
    container_name: kg-ke-eval
    volumes:
      - ../../../:/workspace
      - ke-cache:/workspace/.cache
    environment:
      - CUDA_VISIBLE_DEVICES=3
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

  # 推理系统环境 / Reasoning Systems Environment
  rs-eval:
    build:
      context: ../dockerfiles/reasoning-systems
      dockerfile: Dockerfile
    image: ghcr.io/kg/rs-eval:1.0.0
    container_name: kg-rs-eval
    volumes:
      - ../../../:/workspace
      - rs-cache:/workspace/.cache
    environment:
      - CUDA_VISIBLE_DEVICES=4
      - PYTHONPATH=/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

  # 应用环境 / Applications Environment
  app-eval:
    build:
      context: ../dockerfiles/applications
      dockerfile: Dockerfile
    image: ghcr.io/kg/app-eval:1.0.0
    container_name: kg-app-eval
    volumes:
      - ../../../:/workspace
      - app-cache:/workspace/.cache
    environment:
      - PYTHONPATH=/workspace
      - FLASK_ENV=development
    working_dir: /workspace
    ports:
      - "5000:5000"
      - "8501:8501"
    command: tail -f /dev/null
    networks:
      - kg-network

  # 形式化方法环境 / Formal Methods Environment
  fm-eval:
    build:
      context: ../dockerfiles/formal-methods
      dockerfile: Dockerfile
    image: ghcr.io/kg/fm-eval:1.0.0
    container_name: kg-fm-eval
    volumes:
      - ../../../:/workspace
      - fm-cache:/workspace/.cache
    environment:
      - PYTHONPATH=/workspace
      - COQPATH=/workspace
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

  # 工程实践环境 / Engineering Practice Environment
  ep-eval:
    build:
      context: ../dockerfiles/engineering-practice
      dockerfile: Dockerfile
    image: ghcr.io/kg/ep-eval:1.0.0
    container_name: kg-ep-eval
    volumes:
      - ../../../:/workspace
      - ep-cache:/workspace/.cache
    environment:
      - PYTHONPATH=/workspace
      - KUBECONFIG=/workspace/.kube/config
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

  # 研究方法论环境 / Research Methodology Environment
  rm-eval:
    build:
      context: ../dockerfiles/research-methodology
      dockerfile: Dockerfile
    image: ghcr.io/kg/rm-eval:1.0.0
    container_name: kg-rm-eval
    volumes:
      - ../../../:/workspace
      - rm-cache:/workspace/.cache
    environment:
      - PYTHONPATH=/workspace
      - R_LIBS=/workspace/.R/library
    working_dir: /workspace
    command: tail -f /dev/null
    networks:
      - kg-network

volumes:
  kr-cache:
  gt-cache:
  sa-cache:
  oe-cache:
  ke-cache:
  rs-cache:
  app-cache:
  fm-cache:
  ep-cache:
  rm-cache:

networks:
  kg-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
